routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
	'/',
	[App\Http\Controllers\ArticleController::class, 'index']
)->name('home');

Auth::routes([
	'register' => false,
]);

Route::feeds();

Route::post(
	'articles',
	[App\Http\Controllers\ArticleController::class, 'store']
);

Route::get(
	'articles/creation',
	[App\Http\Controllers\ArticleController::class, 'create']
)->name('articles.create');

Route::get(
	'categories/{category}/articles',
	[App\Http\Controllers\CategoryController::class, 'show']
)->name('categories.show');

Route::get('foire-aux-questions', function () {
	return view('faq');
})->name('faq');

Route::get('hors-ligne', function () {
	return view('offline');
})->name('offline');

Route::post(
	'/articles/create/fetch',
	[App\Http\Controllers\ArticleController::class, 'fetch']
);

Route::middleware(['auth.admin'])->name('admin.')->prefix('admin')->group(function () {
	Route::get(
		'/',
		[App\Http\Controllers\Admin\AdminController::class, 'index']
	)->name('index');

	Route::get(
		'articles/status/{status}',
		[App\Http\Controllers\Admin\ArticleController::class, 'status']
	)->name('articles.status');

	Route::resource('articles', App\Http\Controllers\Admin\ArticleController::class);

	Route::resource('feeds', App\Http\Controllers\Admin\FeedController::class);

	Route::resource('users', App\Http\Controllers\Admin\UserController::class);
});

app/Models/Feed.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Laravel\Scout\Searchable;

/**
 * App\Models\Feed
 *
 * @property int $id
 * @property string $name
 * @property string $slug
 * @property string $url
 * @property string|null $last_sync
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Article[] $articles
 * @property-read int|null $articles_count
 * @method static \Illuminate\Database\Eloquent\Builder|Feed newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Feed newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Feed query()
 * @method static \Illuminate\Database\Eloquent\Builder|Feed whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Feed whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Feed whereLastSync($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Feed whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Feed whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Feed whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Feed whereUrl($value)
 * @mixin \Eloquent
 */
class Feed extends Model
{
	use HasFactory, Searchable;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array<string>
	 */
	protected $fillable = [
		'name',
		'slug',
		'url',
		'last_sync'
	];

	/**
	 * The table associated with the model.
	 *
	 * @var string
	 */
	protected $table = 'feeds';

	/**
	 * The primary key associated with the table.
	 *
	 * @var string
	 */
	protected $primaryKey = 'id';

	/**
	 * Get the articles of the feed.
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany<\App\Models\Article>
	 */
	public function articles() : HasMany
	{
		return $this->hasMany(Article::class);
	}
}

app/Http/Controllers/Admin/FeedController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Article;
use App\Models\Feed;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class FeedController extends Controller
{
	/**
	 * Display a listing of the resource.
	 */
	public function index() : Response
	{
		$feeds = Feed::orderByDesc('id')->paginate(10);

		return response()->view('admin.feeds.index', compact('feeds'));
	}

	/**
	 * Show the form for creating a new resource.
	 */
	public function create() : Response
	{
		return response()->view('admin.feeds.create');
	}

	/**
	 * Store a newly created resource in storage.
	 */
	public function store(Request $request) : RedirectResponse
	{
		$request->validate([
			'name' => 'required||max:255',
			'slug' => 'required|unique:feeds|max:255',
			'url' => 'required|unique:feeds|max:255|url',
		]);

		$feed = Feed::create($request->all());

		return response()->redirectToRoute('admin.feeds.show', $feed->id)
			->with('success', 'Le flux RSS a été créé avec succès.');
	}

	/**
	 * Display the specified resource.
	 */
	public function show(int $id) : Response
	{
		$feed = Feed::findOrFail($id);

		$articles = $feed->articles()->paginate(10);

		return response()->view(
			'admin.feeds.show',
			compact('feed', 'articles')
		);
	}

	/**
	 * Show the form for editing the specified resource.
	 */
	public function edit(int $id) : Response
	{
		$feed = Feed::findOrFail($id);

		return response()->view('admin.feeds.edit', compact('feed'));
	}

	/**
	 * Update the specified resource in storage.
	 */
	public function update(Request $request, int $id) : RedirectResponse
	{
		$request->validate([
			'name' => 'required||max:255',
			'slug' => 'required|unique:feeds,id,' . $id . '|max:255',
			'url' => 'required|unique:feeds,id,' . $id . '|max:255|url',
		]);

		Feed::findOrFail($id)->update($request->all());

		return response()->redirectToRoute('admin.feeds.show', $id)
			->with('success', 'Le flux RSS a été mis à jour avec succès.');
	}

	/**
	 * Remove the specified resource from storage.
	 */
	public function destroy(int $id) : RedirectResponse
	{
		Article::where('feed_id', $id)->update(['feed_id' => null]);
		Feed::findOrFail($id)->delete();

		return response()->redirectToRoute('admin.feeds.index')
			->with('success', 'Le flux RSS a été supprimé avec succès.');
	}
}

resources/views/admin/feeds/create.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>{{ __('admin/feeds.index.create') }}</h1>
</div>

<div class="my-4">
    <div class="col">
        <div class="card">
            <div class="card-body p-3">
                <form method="POST" action="{{ route('admin.feeds.store') }}">
                    @csrf

                    <div class="mb-3">
                        <label for="name" class="form-label">Nom</label>
                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" placeholder="{{ __('Nom') }}" value="{{ old('name') }}" required/>

                        @error('title')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label for="slug" class="form-label">Slug</label>
                        <input id="slug" type="text" class="form-control @error('slug') is-invalid @enderror" name="slug" placeholder="{{ __('Slug') }}" value="{{ old('slug') }}" required/>

                        @error('slug')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label for="url" class="form-label">URL</label>
                        <input id="url" type="text" class="form-control @error('url') is-invalid @enderror" name="url" placeholder="{{ __('URL') }}" value="{{ old('url') }}" required/>

                        @error('url')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-success btn-md text-white">Ajouter un flux RSS</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/feeds/edit.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>Modifier le flux RSS</h1>
    <div>
        <a href="{{ route("admin.feeds.show", $feed->id) }}" class="btn btn-primary text-white me-2">Voir le flux RSS</a>
        <a href="{{ route('admin.feeds.destroy', $feed->id) }}" class="btn btn-danger text-white">Supprimer le flux RSS</a>
    </div>
</div>

<div class="my-4">
    <div class="col">
        <div class="card">
            <div class="card-body p-3">
                <form method="POST" action="{{ route('admin.feeds.update', $feed->id) }}">
                    @csrf
                    @method('PUT')

                    <div class="mb-3">
                        <label for="name" class="form-label">Nom</label>
                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" placeholder="{{ __('Nom') }}" value="{{ old('name', $feed->name) }}" required/>

                        @error('title')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label for="slug" class="form-label">Slug</label>
                        <input id="slug" type="text" class="form-control @error('slug') is-invalid @enderror" name="slug" placeholder="{{ __('Slug') }}" value="{{ old('slug', $feed->slug) }}" required/>

                        @error('slug')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label for="url" class="form-label">URL</label>
                        <input id="url" type="text" class="form-control @error('url') is-invalid @enderror" name="url" placeholder="{{ __('URL') }}" value="{{ old('url', $feed->url) }}" required/>

                        @error('url')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-warning btn-md text-white">Modifier le flux RSS</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/feeds/index.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>{{ __('admin/feeds.index.title') }}</h1>
    <a href="{{ route('admin.feeds.create') }}" class="btn btn-success text-white">{{ __('admin/feeds.index.create') }}</a>
</div>

<div class="my-4 table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">{{ __('Name') }}</th>
              <th scope="col">Dernière synchronisation</th>
              <th scope="col">{{ __('Actions') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($feeds as $feed)
                <tr>
                    <th scope="row">{{ $feed->id }}</th>
                    <td>{{ Str::limit($feed->name, 120) }}</td>
                    <td>{{ \Carbon\Carbon::parse($feed->last_sync)->format('d.m.Y à H:i') }}</td>
                    <td>
                        <div class="btn-group" role="group" aria-label="{{ __('Actions') }}">
                            <a href="{{ route('admin.feeds.show', $feed->id) }}" class="btn btn-primary"><i class="fas fa-eye text-white"></i></a>
                            <a href="{{ route('admin.feeds.edit', $feed->id) }}" class="btn btn-warning"><i class="fas fa-pen text-white"></i></a>
                            <form method="POST" action="{{ route('admin.feeds.destroy', $feed->id) }}">
                                @csrf
                                @method('DELETE')

                                <button type="submit" class="btn btn-danger rounded-0 rounded-end">
                                    <i class="fas fa-trash-alt text-white"></i>
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>

<div class="d-flex justify-content-center">
    {{ $feeds->links() }}
</div>
@endsection

resources/views/admin/feeds/show.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>Détails du flux RSS</h1>
    <div class="d-flex">
        <a href="{{ route('admin.feeds.edit', $feed->id) }}" class="btn btn-warning text-white me-2">Modifier le flux RSS</a>
        <form method="POST" action="{{ route('admin.feeds.destroy', $feed->id) }}">
            @csrf
            @method('DELETE')

            <div class="form-group">
                <input type="submit" class="btn btn-danger text-white" value="Supprimer le flux RSS">
            </div>
        </form>
    </div>
</div>

<div class="row my-4">
    <div class="col">
        <div class="card">
            <div class="card-body py-0">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="row my-2">
                            <span class="col-2 fw-bold">ID</span>
                            <span class="col-10">{{ $feed->id }}</span>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row my-2">
                            <span class="col-2 fw-bold">Nom</span>
                            <span class="col-10">{{ $feed->name }}</span>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row my-2">
                            <span class="col-2 fw-bold">Slug</span>
                            <span class="col-10">{{ $feed->slug }}</span>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row my-2">
                            <span class="col-2 fw-bold">URL</span>
                            <span class="col-10">
                                <a href="{{ $feed->url }}">{{ $feed->url }}</a>
                            </span>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row my-2">
                            <span class="col-2 fw-bold">Dernière synchronisation</span>
                            <span class="col-10">{{ \Carbon\Carbon::parse($feed->last_sync)->format('d.m.Y à H:i') }}</span>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>Articles liés au flux RSS</h1>
</div>

<div class="my-4 table-responsive">
    <div clas="col table-responsive">
        <table class="table table-striped table-hover align-middle">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Titre</th>
                <th scope="col">Statut</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($articles as $article)
                <tr>
                    <th scope="row">{{ $article->id }}</th>
                    <td>{{ Str::limit($article->title, 120) }}</td>
                    @switch($article->status->name)
                        @case('PENDING')
                        <td><span class="badge bg-warning">En attente</span></td>
                        @break

                        @case('PUBLISHED')
                        <td><span class="badge bg-success">Publié</span></td>
                        @break

                        @case('REJECTED')
                        <td><span class="badge bg-danger">Rejeté</span></td>
						@break
                    @endswitch
                    <td>
                        <div class="btn-group" role="group" aria-label="Actions">
                            <a href="{{ route('admin.articles.show', $article->id) }}" class="btn btn-primary"><i class="fas fa-eye text-white"></i></a>
                            <a href="{{ route('admin.articles.edit', $article->id) }}" class="btn btn-warning"><i class="fas fa-pen text-white"></i></a>
                            <a href="{{ route('admin.articles.destroy', $article->id) }}" class="btn btn-danger"><i class="fas fa-trash-alt text-white"></i></a>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <div class="d-flex justify-content-center">
        {{ $articles->links() }}
    </div>
</div>


@endsection