routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
	'/',
	[App\Http\Controllers\ArticleController::class, 'index']
)->name('home');

Auth::routes([
	'register' => false,
]);

Route::feeds();

Route::post(
	'articles',
	[App\Http\Controllers\ArticleController::class, 'store']
);

Route::get(
	'articles/creation',
	[App\Http\Controllers\ArticleController::class, 'create']
)->name('articles.create');

Route::get(
	'categories/{category}/articles',
	[App\Http\Controllers\CategoryController::class, 'show']
)->name('categories.show');

Route::get('foire-aux-questions', function () {
	return view('faq');
})->name('faq');

Route::get('hors-ligne', function () {
	return view('offline');
})->name('offline');

Route::post(
	'/articles/create/fetch',
	[App\Http\Controllers\ArticleController::class, 'fetch']
);

Route::middleware(['auth.admin'])->name('admin.')->prefix('admin')->group(function () {
	Route::get(
		'/',
		[App\Http\Controllers\Admin\AdminController::class, 'index']
	)->name('index');

	Route::get(
		'articles/status/{status}',
		[App\Http\Controllers\Admin\ArticleController::class, 'status']
	)->name('articles.status');

	Route::resource('articles', App\Http\Controllers\Admin\ArticleController::class);

	Route::resource('feeds', App\Http\Controllers\Admin\FeedController::class);

	Route::resource('users', App\Http\Controllers\Admin\UserController::class);
});

app/Models/Article.php
<?php

namespace App\Models;

use App\Enums\ArticleStatus;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Laravel\Scout\Searchable;
use Spatie\Feed\Feedable;
use Spatie\Feed\FeedItem;

/**
 * App\Models\Article
 *
 * @property int $id
 * @property string $url
 * @property string $title
 * @property string $slug
 * @property string $description
 * @property string $author
 * @property string $image
 * @property int $status
 * @property int|null $category_id
 * @property int|null $feed_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\Models\Category|null $category
 * @property-read \App\Models\Feed|null $feed
 * @method static \Illuminate\Database\Eloquent\Builder|Article newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Article newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Article query()
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereAuthor($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereCategoryId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereFeedId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereUrl($value)
 * @mixin \Eloquent
 * @property \Illuminate\Support\Carbon|null $published_at
 * @method static \Illuminate\Database\Eloquent\Builder|Article wherePublishedAt($value)
 */
class Article extends Model implements Feedable
{
	use HasFactory, Searchable;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array<string>
	 */
	protected $fillable = [
		'url',
		'title',
		'slug',
		'description',
		'author',
		'image',
		'status',
		'published_at',
		'category_id',
		'feed_id',
	];

	/**
	 * The table associated with the model.
	 *
	 * @var string
	 */
	protected $table = 'articles';

	/**
	 * The primary key associated with the table.
	 *
	 * @var string
	 */
	protected $primaryKey = 'id';

	/**
	 * Get the category of the article.
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\Category, \App\Models\Article>
	 */
	public function category() : BelongsTo
	{
		return $this->belongsTo(Category::class, 'category_id');
	}

	/**
	 * Get the feed of the article.
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\Feed, \App\Models\Article>
	 */
	public function feed() : BelongsTo
	{
		return $this->belongsTo(Feed::class, 'feed_id');
	}

	/**
	 * The attributes that should be cast to native types.
	 *
	 * @var array<string, string>
	 */
	protected $casts = [
		'email_verified_at' => 'datetime',
		'published_at' => 'datetime',
		'status' => ArticleStatus::class,
	];

	/**
	 * Algolia add attributes
	 */
	public function toSearchableArray() : array
	{
		$array = $this->toArray();

		$array = $this->transform($array);

		$array['category_name'] = "";
		$array['feed_name'] = "";

		if (!is_null($array['category_id']) && !is_null($this->category)) {
			$array['category_name'] = $this->category->name;
		}

		if (!is_null($array['feed_id']) && !is_null($this->feed)) {
			$array['feed_name'] = $this->feed->name;
		}

		return $array;
	}

	/**
	 * Return the feed item for the article.
	 */
	public function toFeedItem(): FeedItem
	{
		return FeedItem::create()
			->id((string) $this->id)
			->title($this->title)
			->summary($this->description)
			->category($this->category ? $this->category->name : "")
			->updated($this->published_at)
			->link($this->url)
			->authorName($this->author)
			->image($this->image);
	}

	/**
	 * Return articles for feed.
	 *
	 * @return \Illuminate\Database\Eloquent\Collection<int, \App\Models\Article>
	 */
	public static function getFeedItems() : Collection
	{
		return Article::where('status', ArticleStatus::PUBLISHED)
			->orderByDesc('published_at')
			->limit(50)
			->with('category')
			->get();
	}
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Enums\ArticleStatus;
use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateArticleRequest;
use App\Models\Article;
use App\Models\Category;
use App\Models\Feed;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Carbon;

class ArticleController extends Controller
{
	/**
	 * Display a listing of the resource.
	 */
	public function index() : Response
	{
		$articles = Article::orderByDesc('created_at')->paginate(10);

		return response()->view('admin.articles.index', compact('articles'));
	}

	/**
	 * Display a listing of the resource by status.
	 */
	public function status(Request $request) : Response
	{
		$articles = Article::orderByDesc('created_at')
			->where('status', $request->status)
			->with('category', 'feed')
			->paginate(10);

		$status = $request->status;

		return response()->view(
			'admin.articles.status',
			compact(['status', 'articles'])
		);
	}

	/**
	 * Display the specified resource.
	 */
	public function show(int $id) : Response
	{
		$article = Article::where('id', $id)->with('category')->first();

		return response()->view('admin.articles.show', compact('article'));
	}

	/**
	 * Show the form for editing the specified resource.
	 */
	public function edit(int $id) : Response
	{
		$article = Article::findOrFail($id);

		$categories = Category::all();

		$feeds = Feed::all();

		return response()->view(
			'admin.articles.edit',
			compact(['article', 'categories', 'feeds'])
		);
	}

	/**
	 * Update the specified resource in storage.
	 */
	public function update(UpdateArticleRequest $request, int $id) : RedirectResponse
	{
		$article = Article::findOrFail($id);

		$validated = $request->validated();

		$article->url = strval($validated['url']);
		$article->title = strval($validated['title']) ;
		$article->slug = strval($validated['slug']);
		$article->description = strval($validated['description']);
		$article->author = strval($validated['author']);

		if ($validated["category"] != null) {
			$article->category_id = intval($validated['category']);
		}

		if ($request->hasFile('image')) {
			$article->image = $validated->photo->storeAs(
				'public/articles',
				$validated['slug'] . '.' . $validated->photo->extension()
			);
		}

		if ($article->status->value != $validated['status']) {
			$article->status = intval($validated['status']);
			$article->published_at = null;

			if ($validated['status'] == ArticleStatus::PUBLISHED->value) {
				$article->published_at = Carbon::now();
			}
		}

		$article->save();

		return response()->redirectToRoute(
			'admin.articles.show',
			$article->id
		)->with('success', "L'article a été mis à jour avec succès.");
	}

	/**
	 * Remove the specified resource from storage.
	 */
	public function destroy(int $id) : RedirectResponse
	{
		$article = Article::findOrFail($id);

		$article->delete();

		return response()->redirectToRoute('admin.articles.index');
	}
}

app/Http/Controllers/Api/ArticleController.php
<?php

namespace App\Http\Controllers\Api;

use App\Enums\ArticleStatus;
use App\Http\Controllers\Controller;
use App\Models\Article;
use Illuminate\Http\JsonResponse;

class ArticleController extends Controller
{

	/**
	 * Display the specified resource.
	 */
	public function index() : JsonResponse
	{
		$articles = Article::where('status', ArticleStatus::PUBLISHED)
			->orderByDesc('published_at')
			->with('category')
			->cursorPaginate(10);

		return response()->json($articles);
	}
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Enums\ArticleStatus;
use App\Http\Requests\StoreArticleRequest;
use App\Mail\ArticleCreated;
use App\Models\Article;
use App\Models\Category;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use OpenGraph;

class ArticleController extends Controller
{
	/**
	 * Display a listing of the resource.
	 */
	public function index() : Response
	{
		$categories = Category::orderBy('slug')->get();

		return response()->view('articles.index', compact('categories'));
	}

	/**
	 * Show the form for creating a new resource.
	 */
	public function create() : Response
	{
		$categories = Category::orderBy('slug')->get();

		return response()->view('articles.create', compact('categories'));
	}

	/**
	 * Store a newly created resource in storage.
	 */
	public function store(StoreArticleRequest $request) : JsonResponse
	{
		$validated = $request->validated();

		$article = new Article;

		$article->url = strval($validated['url']);
		$article->title = strval($validated['title']);
		$article->slug = Str::slug(strval($validated['title']), '-');
		$article->description = strval($validated['description']);
		$article->author = strval($validated['author']);
		$article->image = $this->storeImageToStorage(strval($validated['image']), strval($article->slug));
		$article->status = ArticleStatus::PENDING->value;
		$article->category_id = intval($validated['category']);

		$article->save();

		Mail::to(env('MAIL_TO_ADDRESS'))->send(new ArticleCreated($article));

		return response()->json(['success' => true], 201);
	}

	/**
	 * Store image to storage
	 */
	private function storeImageToStorage(string $image, string $filename) : string
	{
		$parsedImageUrl = parse_url($image, PHP_URL_PATH);
		$extension = pathinfo(strval($parsedImageUrl), PATHINFO_EXTENSION);

		$filename = $filename . '.' . $extension;
		$contents = file_get_contents($image);

		if ($contents !== false) {
			Storage::disk('public')->put('articles/' . $filename, $contents);
		}

		return "/storage/articles/$filename";
	}

	/**
	 * Fetch OpenGraph data for an article.
	 */
	public function fetch(Request $request) : JsonResponse
	{
		if (Article::firstWhere('url', $request->url)) {
			return response()->json(['status' => 'error', 'message' => "L'URL existe déjà."], 409);
		}

		return response()->json([OpenGraph::fetch($request->url)], 200);
	}
}

resources/views/admin/articles/edit.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>Modifier l'article</h1>
    <div>
        <a href="{{ route("admin.articles.show", $article->id) }}" class="btn btn-primary text-white me-2">Voir l'article</a>
        <a href="{{ route('admin.articles.destroy', $article->id) }}" class="btn btn-danger text-white">Supprimer l'article</a>
    </div>
</div>

<div class="my-4">
    <div class="col">
        <div class="card">
            <div class="card-body p-3">
                <form method="POST" action="{{ route('admin.articles.update', $article->id) }}">
                    @csrf
                    @method('PUT')

                    <div class="mb-3">
                        <label for="url" class="form-label">URL</label>
                        <input id="url" type="text" class="form-control @error('url') is-invalid @enderror" name="url" placeholder="{{ __('URL') }}" value="{{ old('url', $article->url) }}" required/>

                        @error('url')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label for="title" class="form-label">Titre</label>
                        <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" placeholder="{{ __('Titre') }}" value="{{ old('title', $article->title) }}" required/>

                        @error('title')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label for="slug" class="form-label">Slug</label>
                        <input id="slug" type="text" class="form-control @error('slug') is-invalid @enderror" name="slug" placeholder="{{ __('Slug') }}" value="{{ old('slug', $article->slug) }}" required/>

                        @error('slug')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label for="description" class="form-label">Description</label>
                        <textarea name="description" id="description" class="form-control @error('description') is-invalid @enderror" rows="2" placeholder="Description">{{ old('description', $article->description) }}</textarea>

                        @error('description')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label for="author" class="form-label">Auteur</label>
                        <input id="author" type="text" class="form-control @error('author') is-invalid @enderror" name="author" placeholder="Auteur" value="{{ old('author', $article->author) }}" required/>

                        @error('author')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label for="image" class="form-label">Image</label>
                        <input id="image" name="image" type="file" class="form-control @error('image') is-invalid @enderror" accept="image/*"/>

                        <figure class="mt-3">
                            <figcaption class="text-muted">Image actuelle</figcaption>
                            <img src="{{ $article->image }}" class="rounded" style="max-height: 300px;"/>
                        </figure>

                        @error('image')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label for="status" class="form-label">Statut</label>
                        <select class="form-select" id="status" name="status" aria-label="Sélectionnez le statut de l'article">
                            @foreach (\App\Enums\ArticleStatus::cases()	 as $status)
                                <option value="{{ $status->value }}" {{ old('status', $article->status) == $status ? "selected" : "" }}>
                                    @switch($status)
                                        @case(\App\Enums\ArticleStatus::PENDING)
                                            En attente
                                            @break

                                        @case(\App\Enums\ArticleStatus::PUBLISHED)
                                            Publié
                                            @break

                                        @case(\App\Enums\ArticleStatus::REJECTED)
                                            Rejeté
                                            @break
                                    @endswitch
                                </option>
                            @endforeach
                        </select>

                        @error('status')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label for="category" class="form-label">Catégorie</label>
                        <select class="form-select" id="category" name="category" aria-label="Sélectionnez la catégorie de l'article">
                            <option value="" selected>Aucune</option>
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}" {{ old('category', $article->category_id) == $category->id ? "selected" : "" }}>{{ $category->name }}</option>
                            @endforeach
                        </select>

                        @error('category')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-warning btn-md text-white">Modifier l'article</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/articles/index.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>Articles</h1>
</div>

<div class="my-4 table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Titre</th>
                <th scope="col">Statut</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($articles as $article)
                <tr>
                    <th scope="row">{{ $article->id }}</th>
                    <td>{{ Str::limit($article->title, 120) }}</td>
                    @switch($article->status)
                        @case(\App\Enums\ArticleStatus::PENDING)
                        <td><span class="badge bg-warning">En attente</span></td>
                        @break

                        @case(\App\Enums\ArticleStatus::PUBLISHED)
                        <td><span class="badge bg-success">Publié</span></td>
                        @break

                        @case(\App\Enums\ArticleStatus::REJECTED)
                        <td><span class="badge bg-danger">Rejeté</span></td>
                    @endswitch
                    <td>
                        <div class="btn-group" role="group" aria-label="Actions">
                            <a href="{{ route('admin.articles.show', $article->id) }}" class="btn btn-primary"><i class="fas fa-eye text-white"></i></a>
                            <a href="{{ route('admin.articles.edit', $article->id) }}" class="btn btn-warning"><i class="fas fa-pen text-white"></i></a>
                            <form method="POST" action="{{ route('admin.articles.destroy', $article->id) }}">
                                @csrf
                                @method('DELETE')

                                <button type="submit" class="btn btn-danger rounded-0 rounded-end">
                                    <i class="fas fa-trash-alt text-white"></i>
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>

<div class="d-flex justify-content-center">
    {{ $articles->links() }}
</div>
@endsection

resources/views/admin/articles/show.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>Détails de l'article</h1>
    <div class="d-flex">
        <a href="{{ route("admin.articles.edit", $article->id) }}" class="btn btn-warning text-white me-2">Modifier l'article</a>
        <form method="POST" action="{{ route('admin.articles.destroy', $article->id) }}">
            @csrf
            @method('DELETE')

            <div class="form-group">
                <input type="submit" class="btn btn-danger text-white" value="Supprimer l'article">
            </div>
        </form>
    </div>
</div>

<div class="my-4">
    <div class="col">
        <div class="card">
            <div class="card-body py-0">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="row my-2">
                            <span class="col-2 fw-bold">ID</span>
                            <span class="col-10">{{ $article->id }}</span>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row my-2">
                            <span class="col-2 fw-bold">URL</span>
                            <span class="col-10">
                                <a href="{{ $article->url }}">{{ $article->url }}</a>
                            </span>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row my-2">
                            <span class="col-2 fw-bold">Titre</span>
                            <span class="col-10">{{ $article->title }}</span>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row my-2">
                            <span class="col-2 fw-bold">Slug</span>
                            <span class="col-10">{{ $article->slug }}</span>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row my-2">
                            <span class="col-2 fw-bold">Description</span>
                            <span class="col-10">{{ $article->description }}</span>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row my-2">
                            <span class="col-2 fw-bold">Auteur</span>
                            <span class="col-10">{{ $article->author }}</span>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row my-2">
                            <span class="col-2 fw-bold">Image</span>
                            <span class="col-10">
                                <img src="{{ $article->image }}" class="img-fluid" style="max-height: 400px;"/>
                            </span>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row my-2">
                            <div class="col-2 fw-bold">Statut</div>
                            <div class="col-10">
                                @switch($article->status)
                                    @case(\App\Enums\ArticleStatus::PENDING)
                                    <span class="badge bg-warning fs-6">En attente</span>
                                    @break

                                    @case(\App\Enums\ArticleStatus::PUBLISHED)
                                    <span class="badge bg-success fs-6">Publié</span>
                                    @break

                                    @case(\App\Enums\ArticleStatus::REJECTED)
                                    <span class="badge bg-danger fs-6">Rejeté</span>
                                @endswitch
                            </div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row my-2">
                            <span class="col-2 fw-bold">Catégorie</span>
                            <span class="col-10">{{ $article->category_id ? $article->category->name : "" }}</span>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/articles/status.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>{{ __("admin.index.status.${status}") }}</h1>
</div>

<div class="my-4 table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Catégorie</th>
                <th scope="col">Titre</th>
                <th scope="col">Flux RSS</th>
                <th scope="col">Date de création</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($articles as $article)
                <tr>
                    <th scope="row">{{ $article->id }}</th>
                    <th>{{ $article->category ? $article->category->name : '' }}</th>
                    <td>{{ Str::limit($article->title, 120) }}</td>
                    <td>{{ $article->feed ? $article->feed->name : '' }}</td>
                    <td>{{ $article->created_at->diffForHumans() }}</td>
                    <td>
                        <div class="btn-group" role="group" aria-label="Actions">
                            <a href="{{ route('admin.articles.show', $article->id) }}" class="btn btn-primary"><i class="fas fa-eye text-white"></i></a>
                            <a href="{{ route('admin.articles.edit', $article->id) }}" class="btn btn-warning"><i class="fas fa-pen text-white"></i></a>
                            <a href="{{ route('admin.articles.destroy', $article->id) }}" class="btn btn-danger"><i class="fas fa-trash-alt text-white"></i></a>
                        </div>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>

<div class="d-flex justify-content-center">
    {{ $articles->links() }}
</div>
@endsection