routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
	'/',
	[App\Http\Controllers\ArticleController::class, 'index']
)->name('home');

Auth::routes([
	'register' => false,
]);

Route::feeds();

Route::post(
	'articles',
	[App\Http\Controllers\ArticleController::class, 'store']
);

Route::get(
	'articles/creation',
	[App\Http\Controllers\ArticleController::class, 'create']
)->name('articles.create');

Route::get(
	'categories/{category}/articles',
	[App\Http\Controllers\CategoryController::class, 'show']
)->name('categories.show');

Route::get('foire-aux-questions', function () {
	return view('faq');
})->name('faq');

Route::get('hors-ligne', function () {
	return view('offline');
})->name('offline');

Route::post(
	'/articles/create/fetch',
	[App\Http\Controllers\ArticleController::class, 'fetch']
);

Route::middleware(['auth.admin'])->name('admin.')->prefix('admin')->group(function () {
	Route::get(
		'/',
		[App\Http\Controllers\Admin\AdminController::class, 'index']
	)->name('index');

	Route::get(
		'articles/status/{status}',
		[App\Http\Controllers\Admin\ArticleController::class, 'status']
	)->name('articles.status');

	Route::resource('articles', App\Http\Controllers\Admin\ArticleController::class);

	Route::resource('feeds', App\Http\Controllers\Admin\FeedController::class);

	Route::resource('users', App\Http\Controllers\Admin\UserController::class);
});

resources/views/layouts/admin/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

	<meta name="robots" content="noindex">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Tableau de bord - {{ config('app.name', 'Laravel') }}</title>

    <!-- Description -->
    <meta name="description" content="participer.info est une plateforme qui a pour but de partager des articles, vidéos, news, etc., afin de mettre en avant les visions alternatives des citoyens.">

    <!-- Favicon -->
    <link rel="shortcut icon" href="{{ asset('favicon.ico') }}">

    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">

    <!-- Manifest -->
    <link rel="manifest" href="/manifest.json">
</head>
<body>
    @include('layouts.admin.header')

    <div class="container-fluid">
        <div class="row">
            @include('layouts.admin.nav')

            <div id="app">
                <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                    <admin-search></admin-search>

                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    @yield('content')
                </main>
            </div>
        </div>
    </div>
    <!-- Scripts -->
    <script src="{{ asset('js/manifest.js') }}"></script>
    <script src="{{ asset('js/vendor.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script type="text/javascript">
        // Initialize the service worker
        window.addEventListener('load', () => {
            if ('serviceWorker' in navigator) {
                console.log('Service worker is supported');
                navigator.serviceWorker.register('/sw.js', { scope: '/' }).then(registration => {
                    console.log('Service worker is registered', registration);
                }).catch(error => {
                    console.log('Service worker registration failed', error);
                });
            }
        });
    </script>
</body>
</html>

resources/views/layouts/admin/header.blade.php
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{{ route('admin.index') }}">{{ config('app.name', 'Laravel') }}</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-nav d-none d-md-block">
        <div class="nav-item text-nowrap">
            <a class="nav-link px-3" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">{{ __('Logout') }}</a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </div>
    </div>
</header>

resources/views/layouts/admin/nav.blade.php
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link {{ Route::is('admin.index') ? 'active' : '' }}" aria-current="page" href="{{ route('admin.index') }}">
                    <i class="fa-solid fa-chart-line"></i>
                    {{ __('admin.layout.nav.dashboard') }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ Route::is('admin.articles.*') ? 'active' : '' }}" href="{{ route('admin.articles.index') }}">
                    <i class="fa-regular fa-newspaper"></i>
                    {{ __('admin.layout.nav.items') }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ Route::is('admin.feeds.*') ? 'active' : '' }}" href="{{ route('admin.feeds.index') }}">
                    <i class="fa-solid fa-rss"></i>
                    {{ __('admin.layout.nav.feeds') }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link  {{ Route::is('admin.users.*') ? 'active' : '' }}" href="{{ route('admin.users.index') }}">
                    <i class="fa-solid fa-users"></i>
                    {{ __('admin.layout.nav.users') }}
                </a>
            </li>
            <li class="nav-item d-md-none">
                <a class="nav-link px-3" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    <i class="fa-solid fa-right-from-bracket"></i>
                    {{ __('Logout') }}
                </a>
            </li>
        </ul>
    </div>
</nav>